name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  run-postman-collection:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run "wms_easy_ecom_intergration.postman_collection.json" \
        -e "wms_staging.postman_environment.json" \
        --reporters cli,junit \
        --reporter-junit-export results.xml

    - name: Upload Newman Report
      uses: actions/upload-artifact@v3
      with:
        name: postman-report
        path: results.xml
