name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  run-postman-collection:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman and Reporters
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman Collection and Export Reports
      run: |
        newman run "wms_easy_ecom_intergration.postman_collection.json" \
          -e "wms_staging.postman_environment.json" \
          --reporters cli,json,html \
          --reporter-json-export results.json \
          --reporter-html-export postman-report.html

    - name: Create Email Summary Body
      run: |
        node parse-summary.js

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: postman-html-report
        path: postman-report.html

    - name: Send Email with Report Summary and Attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Postman Test Report
        to: shashank.garg@prozo.com
        from: Prozo WMS Bot <${{ secrets.EMAIL_USERNAME }}>
        content_type: html
        body: file://email-body.html
        attachments: postman-report.html
