name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  run-postman-collection:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman Collection
      run: |
        newman run "wms_easy_ecom_intergration.postman_collection.json" \
        -e "wms_staging.postman_environment.json" \
        --reporters cli,junit,html \
        --reporter-junit-export results.xml \
        --reporter-html-export postman-report.html

    - name: Upload JUnit Report
      uses: actions/upload-artifact@v4
      with:
        name: junit-report
        path: results.xml

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: postman-html-report
        path: postman-report.html

    - name: Parse JUnit XML and Generate Email Body
      run: node parse-summary.js
      env:
        SUMMARY_OUTPUT_FILE: email-body.html

    - name: Send Email with Report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Postman Test Report"
        to: shashank.garg@prozo.com
        from: Prozo WMS Bot <${{ secrets.EMAIL_USERNAME }}>
        content_type: text/html
        body: ${{ steps.email-summary.outputs.body }}
        attachments: postman-report.html

    - name: Output Email Summary as Step Output
      id: email-summary
      run: |
        echo "body<<EOF" >> $GITHUB_OUTPUT
        cat email-body.html >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT